# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-24 00:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimedTask',
            fields=[
                ('periodictask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_celery_beat.PeriodicTask')),
                ('nice_name', models.CharField(blank=True, default='', max_length=255)),
                ('host', models.CharField(blank=True, max_length=255, null=True)),
            ],
            bases=('django_celery_beat.periodictask',),
        ),
    ]
